development:
  PERSONAL_WEBSITE_USERNAME: 'postgres'
  PERSONAL_WEBSITE_PASSWORD: 'Lambch0p'
production:
  PERSONAL_WEBSITE_USERNAME: postgres
  PERSONAL_WEBSITE_PASSWORD: Lambch0p
test:
  PERSONAL_WEBSITE_USERNAME: postgres
  PERSONAL_WEBSITE_PASSWORD: Lambch0p
